[package]
name = "plnentity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "plnentity"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0" }
bdk = { git = "https://github.com/bitcoindevkit/bdk", rev = "fbd98b4c5a88a10f8dfc22b4c54187eba4d68afe" }

[dependencies.sea-orm]
version = "^0.7.1"
features = [
  "sqlx-mysql",
  "sqlx-postgres",
  "sqlx-sqlite", 
  "runtime-tokio-rustls", 
  "macros",
  "debug-print",
  "with-chrono"
]
