[package]
name = "plnmigration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "plnmigration"
path = "src/lib.rs"

[dependencies]
sea-schema = { version = "^0.7.1", default-features = false, features = [ "migration", "debug-print" ] }
plnentity = { path = "../plnentity" }
