name: Docker Image Build

on:
  workflow_call:
    inputs:
      version:
        description: The version for the build to be tagged with
        required: true
        type: string
      context_path:
        description: Path to Docker context
        required: false
        type: string
        default: '.'
      dockerfile_path:
        description: Path to Dockerfile to be built
        required: false
        type: string
        default: 'Dockerfile'
      docker_registry:
        description: Docker registry to log in to
        required: false
        type: string
        default: ''
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASS:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64 ]
    steps:
    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build ${{ matrix.arch }} image
      run: |
        docker buildx build \
          --label org.opencontainers.image.title=${{ env.REPO }} \
          --label org.opencontainers.image.revision=${{ github.sha }} \
          --label org.opencontainers.image.version=${{ inputs.version }} \
          --platform linux/${{ matrix.arch }} \
          --file ${{ inputs.dockerfile_path }} \
          --tag ${{ inputs.docker_registry }}/${{ env.REPO }}:${{ inputs.version }}-${{ matrix.arch }} \
          --push \
          ${{ inputs.context_path }}

  manifest:
    needs: [ build_and_push ]
    runs-on: ubuntu-latest
    steps:
    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Create and push multi-platform manifest
      run: |
        docker manifest create \
          ${{ inputs.docker_registry }}/${{ env.REPO }}:${{ inputs.version }} \
          ${{ inputs.docker_registry }}/${{ env.REPO }}:${{ inputs.version }}-amd64
        docker manifest push ${{ inputs.docker_registry }}/${{ env.REPO }}:${{ inputs.version }}
