name: Tags

on:
  push:
    tags: [ 'v*' ]

jobs:
  docker_build:
    uses: ./.github/workflows/docker_build.yaml
    with:
      repo: ${{ github.repository }}
      version: ${{ github.ref_name }}
      docker_registry: ghcr.io
    secrets:
      DOCKER_USER: ${{ github.actor }}
      DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
